tunnel: 0e18aacd-82cf-4978-bcf2-e9a7f8ca8af9
credentials-file: C:\Users\henri\.cloudflared\08d11485-1dad-40de-acdf-a2ef6853a53e.json

ingress:
  # Route all traffic to Flask backend
  - service: http://localhost:3000
    originRequest:
      noTLSVerify: true
